version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: user-management-database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Pinalistas2024
      POSTGRES_DB: user-management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
