@startuml US500

actor Utilizador
participant "RobDroneGo" as Sistema
participant "Frontend" as UI
participant "Gestão Tarefas" as G.Tarefas
participant "Planeamento" as Planeamento

Utilizador -> Sistema : Planear tarefas;
activate Sistema

Sistema -> UI: Planear tarefas;
activate UI

UI -> G.Tarefas : Busca tarefas aprovadas não planeadas;
activate G.Tarefas
G.Tarefas -> UI :  Lista de tarefas aprovadas não planeadas/erro ao obter tarefas;
deactivate G.Tarefas
UI -> Sistema : Lista de tarefas aprovadas não planeadas/erro ao obter tarefas;
deactivate UI
Sistema -> Utilizador : Mostra tarefas aprovadas não planeadas/erro ao obter tarefas;
deactivate Sistema

Utilizador -> Sistema : Seleciona tarefas para planear;
activate Sistema
Sistema -> UI : Lista de tarefas selecionadas para planear;
activate UI
UI -> G.Tarefas : Lista de tarefas selecionadas para planear;
activate G.Tarefas
G.Tarefas -> Planeamento : Lista de tarefas selecionadas para planear;
activate Planeamento
Planeamento -> Planeamento: Planeia tarefas selecionadas;
Planeamento -> G.Tarefas : Sequência de tarefas planeadas/erro ao planear tarefas;
deactivate Planeamento
G.Tarefas -> UI:  Sequência de tarefas planeadas/erro ao planear tarefas;
deactivate G.Tarefas
UI -> Sistema :  Sequência de tarefas planeadas/erro ao planear tarefas;
deactivate UI
Sistema -> Utilizador : Mostra sequência de tarefas planeadas/erro ao planear tarefas;
deactivate Sistema

@enduml