#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - cd Gestao_Informacao
              - npm install
              - npm test
              - npm install -g newman
              - |
                set +e  # Ignore newman fails, it should work when backend is running remotely
                newman run tests/RobDroneGo.postman_collection.json -e tests/RobDroneGoEnv.postman_environment.json
                set -e
