version: '3.1'
services:
  mongo:
    container_name: mongo-docker
    ports:
      - '27017:27017'
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
