
export const edAfloor1_edBfloor2 =[
        {   
            "openMap":"assets/buildings/EdificioA_piso_1.json",
            "openMapInitialPosition":[5,10],
            "caminho":[[5,11],[5,12],[5,13],[5,14],[5,15],[5,16],[5,17],[5,18],[6,19],[7,20],[8,20],[9,20]],
            "elevador":true,
            "bridge":false,
            "map":"assets/buildings/EdificioA_piso_2.json",
            "initialPosition":[2.1,20]
       },
        {
            "caminho":[[1,20],[0,20],[-1,20],[-1,21],[-1,22]],
            "elevador":false,
            "bridge":true,
            "map":"assets/buildings/EdificioB_piso_2.json",
            "initialPosition":[9,21]
      }
    ];
export const edAfloor1_edAfloor2 = [
        {
            "openMap":"assets/buildings/EdificioA_piso_1.json",
            "openMapInitialPosition":[5,10],
            "caminho":[[5,11],[5,12],[5,13],[5,14],[5,15],[5,16],[5,17],[5,18],[6,19],[7,20],[8,20],[9,20]],
            "elevador":true,
            "bridge":false,
            "map":"assets/buildings/EdificioA_piso_2.json",
            "initialPosition":[2.1,20]
       }
    ];
export const edAfloor2_edBfloor2=[
        {
            "openMapInitialPosition":[2.1,20],
            "openMap":"assets/buildings/EdificioA_piso_2.json",
            "caminho":[[1,20],[0,20],[-1,20],[-1,21],[-1,22]],
            "elevador":false,
            "bridge":true,
            "map":"assets/buildings/EdificioB_piso_2.json",
            "initialPosition":[9,21]
        }
    ];
export const edAfloor1_edCfloor2 =[
        {   
            "openMap":"assets/buildings/EdificioA_piso_1.json",
            "openMapInitialPosition":[5,10],
            "caminho":[[5,11],[5,12],[5,13],[5,14],[5,15],[5,16],[5,17],[5,18],[6,19],[7,20],[8,20],[9,20]],
            "elevador":true,
            "bridge":false,
            "map":"assets/buildings/EdificioA_piso_2.json",
            "initialPosition":[2.1,20]
       },
        {
            "caminho":[[1,20],[0,20],[-1,20],[-1,21],[-1,22]],
            "elevador":false,
            "bridge":true,
            "map":"assets/buildings/EdificioB_piso_2.json",
            "initialPosition":[9,21]
      },
      {
            "caminho":[[1,20]],
            "elevador":false,
            "bridge":true,
            "map":"assets/buildings/EdificioC_piso_2.json",
            "initialPosition":[11,9]
        }
    ];
export const edBfloor2_edCfloor2 =[
      {
            "openMap":"assets/buildings/EdificioB_piso_2.json",
            "openMapInitialPosition":[9,21],
            "caminho":[[9,21]],
            "elevador":false,
            "bridge":true,
            "map":"assets/buildings/EdificioC_piso_2.json",
            "initialPosition":[11,9]
        }
    ];
export const edBfloor2_edBfloor1 =[
        {
              "openMap":"assets/buildings/EdificioB_piso_2.json",
              "openMapInitialPosition":[9.5,21],
              "caminho":[[10,20],[11,19],[12,19],[12,20]],
              "elevador":true,
              "bridge":false,
              "map":"assets/buildings/EdificioB_piso_1.json",
              "initialPosition":[6.5,19.5]
          }
      ];
export const edBfloor1_edBfloor2 =[
        {
              "openMap":"assets/buildings/EdificioB_piso_1.json",
              "openMapInitialPosition":[4.5,18],
              "caminho":[[2,18],[1,18],[1,19],[1,20]],
              "elevador":true,
              "bridge":false,
              "map":"assets/buildings/EdificioB_piso_2.json",
              "initialPosition":[6.5,19.5]
          }
      ];