@startuml US150

participant "Route" as Route
participant "Controller" as Controller
participant "Service" as Service
participant "Repositorio" as Repositorio
participant "DTO" as DTO

-> Route : post(api/buildings)
activate Route
Route -> Controller : createBuilding
activate Controller
Controller -> Service : createBuilding
activate Service
Controller -> Service : buildingDTO
activate DTO
Service -> DTO : buildingDTO
DTO --> Service : DTObuilding
Service -> Repositorio : save(DTObuilding)
activate Repositorio
Service --> Controller : DTObuilding
Controller--> Route : Resposta HTTP
Route --> : Resposta HTTP

@enduml
