@startuml US270

participant "Route" as Route
participant "Controller" as Controller
participant "Service" as Service
participant "Repositorio" as Repositorio


 -> Route : post(api/elevators)
activate Route
Route -> Controller : createElevator()
activate Controller
Controller -> Service : createElevator()
activate Service
Controller -> Service : elevatorDTO
Service -> Repositorio : save(DTOelevator)
activate Repositorio
Service --> Controller : DTOelevator
Controller--> Route : Resposta HTTP
Route --> : Resposta HTTP
note right of Service
O DTO não está representado por questões de simplicidade (Ver US150).
end note
@enduml
