@startuml US250
actor Utilizador
participant "Sistema" as Sistema
Utilizador -> Sistema : Solicita editar passagem entre edificios
activate Sistema
Sistema --> Utilizador : Confirmação de passagem entre edificios editada
deactivate Sistema
@enduml