@startuml US280
actor Utilizador
participant "Sistema" as Sistema
Utilizador -> Sistema : Solicita editar elevador em edificio
activate Sistema
Sistema --> Utilizador : Confirmação de elevador em edificio editado
deactivate Sistema
@enduml