@startuml
title US180 - Listar edifícios com min e max de pisos

participant "Route" as Route
participant "Controller" as Controller
participant "Service" as Service
participant "Repositorio" as Repositorio

 -> Route : get(api/buildings/minmaxfloors)
activate Route
Route -> Controller : getBuildingsByMinMaxFloors()
activate Controller
activate Service
Controller -> Service: getBuildingsByMinMaxFloors(minFloors, maxFloors)
activate Repositorio
Service -> Repositorio : buildingsByFloor=getBuildingsByMinMaxFloors(minFloors, maxFloors)
Service -> Repositorio : findByDomainId(buildingsByFloor)

Service --> Controller : floorDTOs
Controller--> Route : Resposta HTTP
<-- Route : Resposta HTTP

note right of Service
O DTO não está representado por questões de simplicidade (Ver US150).
end note
@enduml
